### PR TITLE
Enable PDF font subsetting with HarfBuzz

### LINKED ISSUE #248: PDF font subsetting
https://github.com/rust-skia/rust-skia/blob/641b03789b71b66a716df19343dfcf7e0cb825bb/skia-bindings/build_support/skia.rs#L148

I'd like to be able to use sfntly to subset fonts, but it's currently disabled.

### PR DESCRIPTION
**Pull request by messense**
Fixes #248

### CODE REVIEW

**Comment by pragmatrix** [comment]
Looks like networking problems on Azure. I am rerunning the tests.

**Comment by pragmatrix** [comment]
While the Windows builds can't download LLVM 9 from chocolately, which is most likely their problem and will be fixed soon, the Linux and macOS builds fail because of linker errors. 

Enabling pdf subsetting embeds the icu library into the skia.lib growing by about 14mb. This in turn causes duplicated symbols, because the skshaper.lib already contains the icu library.

I do have a idea to fix that and will take a closer look later this day.

**Comment by messense** [comment]
@pragmatrix Could you elaborate on how to fix the build issue? I could give it a try.

**Comment by pragmatrix** [comment]
@messense Highly appreciated, I was able to buid Skia with PDF font subsetting with the following patch on MacOS:

```patch
diff --git a/modules/skshaper/BUILD.gn b/modules/skshaper/BUILD.gn
index a672d984f..a8b8bb39d 100644
--- a/modules/skshaper/BUILD.gn
+++ b/modules/skshaper/BUILD.gn
@@ -19,6 +19,7 @@ if (skia_enable_skshaper) {
   }

   component("skshaper") {
+    complete_static_lib = false
     check_includes = false
     import("skshaper.gni")
     public_configs = [ ":public_config" ]
diff --git a/third_party/icu/BUILD.gn b/third_party/icu/BUILD.gn
index 50157f0bf..db72569f6 100644
--- a/third_party/icu/BUILD.gn
+++ b/third_party/icu/BUILD.gn
@@ -68,6 +68,7 @@ if (skia_use_system_icu) {
   }

   third_party("icu") {
+    complete_static_lib = false
     public_include_dirs = [
       "../externals/icu/source/common",
       "../externals/icu/source/i18n",
```

I think this might need to be added to the skshaper.patch in the skia-bindings package to get the build working.

**Comment by pragmatrix** [comment]
Also related is the Skia build flag `is_component_build`.

**Comment by messense** [comment]
It works.

**Comment by pragmatrix** [comment]
Yes, that's very encouraging, I am doing some more builds to see how the size of the binaries change and if the shaper only feature build will work, too.

**Comment by pragmatrix** [comment]
For the record: In `textlayout` feature builds the `icu.lib` is embedded into the `skia.lib`, with `shaper` only feature builds it stays in `skshaper.lib`. Both configurations should be compatible with the prebuilt binaries but must be tested individually before the next release. If anything gets more complicated than that, I am considering to remove the "shaper" feature, because I assume that everyone will use skparagaph / textlayout anyway.

**Comment by pragmatrix** [comment]
`shaper` only builds seem to work, and the size of release build binaries increases about 280kb (tested on MacOS), but only if the textlayout functions are actually used. Given that the resulting executables are usually in the 20mb range, I think that it is reasonable to add PDF subsetting by default instead of adding a new feature flag. 

So I am merging this. Thank you @messense.

**Pull request merged**
