### PR TITLE
note that libjpeg-turbo may also fail to compile on macOS when the SD…

### PR DESCRIPTION
**Pull request by pragmatrix**
…K headers were not properly installed

Details are in this comment: https://github.com/rust-skia/rust-skia/issues/103#issuecomment-490737066

### CODE REVIEW

**Comment by therealbnut** [comment]
It took some searching to know it was `libjpeg-turbo`, you might want to include reference to `SkJpegUtility.cpp` in a similar way that you referred to `TargetConditionals.h`

**Comment by therealbnut** [comment]
This is the post where I found out it was libjpeg-turbo, perhaps using those error messages might be more representative:
https://groups.google.com/forum/#!msg/skia-discuss/OkMe3HWoV-U/Hxs872ySAgAJ

**Comment by pragmatrix** [comment]
I wasn't able to reproduce the build problem of `SkJpegUtility.cpp`, but had the same error once when I integrated the M74 branch (#68).

**Comment by pragmatrix** [comment]
[Rendered](https://github.com/rust-skia/rust-skia/blob/macos-libjpeg-turbo-readme/README.md)

**Comment by therealbnut** [comment]
I think Skia specifically searches for the system python, and needs the symlinked dir `/usr/local/opt/python2` iirc. I believe I had 2.7 via brew in my `$PATH`, but Skia didn't find that. Perhaps you need to remove the system's symlink to replicate the issue I had.

Although IMO you've already gone above and beyond, thank you :) I think these issues are mainly with `skia`, not `rust-skia`.

**Comment by pragmatrix** [comment]
There is something wrong with the azure pipelines, unlikely to be related to the changes. I am merging this. @therealbnut Thank you for taking a look at the changes, I would very much be interested in your further endeavor to use Skia with Rust.

**Comment by therealbnut** [comment]
@pragmatrix thanks, at the moment we're just doing an exploration of various libraries and it looks pretty promising, I'll let you know if we end up using it, or why we didn't if we don't.

Out of interest, do you know any big projects using it? what's driving the development at the moment?

**Comment by pragmatrix** [comment]
Thank you, tell us if there is something missing from it that would block your plans. 

I don't know of _any_ projects using it yet. My personal motivation is to get a deeper grasp of Rust and in the long term to create a development environment for native applications in which all possible states can be simulated _and tested_ anytime, in every detail, and in non-real-time. @Brooooooklyn and @M-Adoo seem to be interested in a WebAssembly port, of which I am not aware of the details.

**Pull request merged**
