### PR TITLE
fix example: Only resize when size is > 0

### PR DESCRIPTION
**Pull request by marc2332**
Hey Armin

What do you think about my changes? 

`NonZeroU32` panics when the value is 0, and this happens when you minimize the window, with my changes it works now :)

### CODE REVIEW

**Comment by pragmatrix** [comment]
Thank you Marc. With this change, the surface keeps the size before the minimization. Should't it be resized to max(width, 1) and max(height, 1), so that the associated memory is freed?

**Comment by marc2332** [comment]
> Thank you Marc. With this change, the surface keeps the size before the minimization. Should't it be resized to max(width, 1) and max(height, 1), so that the associated memory is freed?

That sounds better 😅Sorry 😁 

just pushed!

**Comment by marc2332** [comment]
Seems like the CI randomly failed 😵‍💫🥴😁😆

**Comment by pragmatrix** [comment]
Looks like networking problems.

**Pull request merged**
