### PR TITLE
Experiment: Build with --target wasm32-unknown-emscripten

### LINKED ISSUE #39: Support WebAssembly
Followup from https://github.com/rust-skia/rust-skia/issues/24#issuecomment-471984934 

We ~~need~~ want to support WebAssembly.

### PR DESCRIPTION
**Pull request by pragmatrix**
This PR is an humble experiment to build Skia, skia-bindings, and skia-safe with `--target wasm32-unknown-emscripten`.

In addition to the regular build prerequisites noted in the README, this PR requires [emscripten](https://emscripten.org/docs/getting_started/downloads.html) to be installed.

So far I've only managed to build Skia, skia-bindings, and skia-safe on Ubuntu 19 but anything beyond that, for example linking an example application fails.

Any help is appreciated.

Status:

- [ ] Ubuntu 18 / 19
  - [x] skia-bindings
    - [x] Skia
    - [x] skia-bindings lib
    - [x] bindings.rs
  - [x] skia-safe
  - [ ] example: skia-org
- [ ] macOS
  - [ ] skia-bindings
    - [ ] Skia
    - [ ] skia-bindings lib
    - [ ] bindings.rs
  - [ ] skia-safe
  - [ ] example: skia-org
- [ ] Windows
  - [ ] skia-bindings
    - [ ] Skia
    - [ ] skia-bindings lib
    - [ ] bindings.rs
  - [ ] skia-safe
  - [ ] example: skia-org

I'll try to keep this PR up to date so that anyone who likes to help can step in anytime (PR against my branch).

Closes #39

### CODE REVIEW

**Comment by matheus23** [comment]
I'd love wasm support in rust-skia!

Did this PR use the CPU backend for rendering?

This is how [canvaskit initializes skia with a webgl backend](https://github.com/google/skia/blob/a551fd288101fe082fb9fde12a21fbb0b9765d03/modules/canvaskit/canvaskit_bindings.cpp#L154-L180).

I'm just thinking out loud. I'd like to get this going, but it might be a little hard for me, given my lack of experience with C/C++ and linkers :D

**Comment by pragmatrix** [comment]
At the time I've made this experiment, OpenGL was activated by default, but now I guess it's better to try without hardware acceleration first. The first thing to do is to base this branch on the latest version of the rust-skia repository and see how far we get with all the updated dependencies and toolsets.

**Comment by matheus23** [comment]
So. Good news: Rebasing works without conflicts and `cargo build` runs smoothly.

I'm now trying to setup a new example. This turns out to be quite hard, if I try to use `--target=wasm32-unknown-emscripten`. It works, it generates a .wasm. But how do I use that one? Can I even bind to javascript like that? I'm unfortunately a little new to that.
Looking up online, [everyone seems to recommend wasm32-unknown-unknown](https://users.rust-lang.org/t/wasm-unknown-vs-emscripten/22997/7), but I assume emscripten is needed to successfully compile skia?

I need to understand some things here, before going forward. Note to myself: Maybe looking at how canvaskit is built helps.

**Comment by pragmatrix** [comment]
@matheus23 Sounds great, if you'd like to open a new PR, go on, I'll close this in favor of it.

**Comment by StringKe** [comment]
Is there any progress?

**Comment by matheus23** [comment]
@StringKe I tried to get this working, but I just know too little about the skia build process and rust wasm to be able to get this working, even though I'd love to.
I'm not working on this right now, so no duplicated efforts if anyone wants to pick this up :+1:

**Comment by ctrlcctrlv** [comment]
I've thought about the potential of this on and off for MFEK project, especially MFEKglif, but I don't know what purpose it would serve for us other than "try MFEKglif in your browser!"

Which, to be certain, is a really cool feature. But also, something that's very "late stage" in our project which is just now leaving alpha and approaching beta.

If anyone with the relevant experience wants to be paid to do this, feel free to email the email in my bio, and we can work something out, keeping in mind that it's open source so won't pay amazingly. :-P

**Comment by StringKe** [comment]
I tried to encapsulate the bindings myself, but failed. Has anyone made any progress?

**Comment by pragmatrix** [comment]
Closed in favor of #611

**Pull request closed without merging**
