### PR TITLE
Add the Examples from skia.org's SkCanvas Overview

### PR DESCRIPTION
**Pull request by pragmatrix**
From the website:

https://skia.org/user/api/skcanvas_overview

And here is ours (windows):

heptagram

rotated-rectangle

hello-skia

Looks fine to me. The difference in the size of the image in the third picture's lower right is because I've scaled up the canvas twofold.

### CODE REVIEW

**Comment by pragmatrix** [comment]
ok: fixed (the downloaded image from the website had the wrong size): 

hello-skia

**Comment by pragmatrix** [comment]
Linux seems to work, too, tested on Ubuntu 18 (default font differs): 

hello-skia

**Comment by pragmatrix** [comment]
MacOSX 10.13.

hello-skia

**Comment by M-Adoo** [comment]
nice job.

**Pull request merged**
