### PR TITLE
Support offline builds

### PR DESCRIPTION
**Pull request by pragmatrix**
An initial rough idea on how offline builds can be implemented like suggested in #340.

### CODE REVIEW

**Comment by theotherjimmy** [comment]
Finally looking at this, and it strikes me as odd that we allow a packager to provide their own ninja executable, but we assume that the gn executable will be provided as part off the source. Would it make sense to expect the packager to provide gn as well as ninja?

**Comment by pragmatrix** [comment]
That distinction comes from the fact that ninja was pulled from the depot_tools repository and gn is already contained in Skia's repository, which could lead to the assumption that gn is more tightly coupled to the Skia sources than ninja. But since I don't know how they differ in terms of evolution in relation to the source, the distinction could also be solely justified by that fact that adding another dependency is not needed, because gn must available anyway and is guaranteed to be the correct version to use. 

If you think there is a use case for a separate gn, we should add another environment variable. Although I personally would delay that until an actual use case comes up to get the chance to learn from that.

**Comment by pragmatrix** [comment]
Oh, looking closer at the source I just recognized that git-sync-deps is most probably responsible to fetch the gn executable, which looks like a platform dependent executable (I assumed that it's just a python script). So I think now that you are right, and adding an environment variable is probably the best way to externalize all platform specific dependencies.

**Comment by pragmatrix** [comment]
I've added `SKIA_OFFLINE_GN_COMMAND` environment variable. If set, it should contain the full path to the gn executable that shall be used instead of the default path.

**Comment by pragmatrix** [comment]
I've added some lines of documentation for the environment variables ([rendered](https://github.com/pragmatrix/rust-skia/blob/offline-builds/skia-bindings/README.md#offline-builds)) and would like to merge this as soon as possible to get this MR into the Milestone 84 release.

**Comment by pragmatrix** [comment]
@theotherjimmy Thank you for helping and making offline build support possible. I am merging this now and will close #340 after that, please open new issues if new information comes up.

**Pull request merged**
