### PR TITLE
Add support for using a locally built Skia library

### PR DESCRIPTION
**Pull request by therealbnut**
This PR does two main things:

 * adds a `build-from-source` feature
 * adds environment variables to support using a locally built skia library (`SKIA_BUILD_DEFINES` and `SKIA_LIBRARY_SEARCH_PATH`).

My intention is to use this to simplify the build process with external build systems (nix+bazel).

Most of the changes in this PR are moving code without changing functionality, primarily `skia-bindings/build_support/skia.rs` has been split into multiple parts:

 * `build_support/binaries_config.rs`
 * `build_support/bind_skia.rs`
 * `build_support/build_skia`
 * `build_support/features.rs`

I've tested this on mac under these conditions:

```bash
cargo build
```

```bash
cargo test --all --features=textlayout,use-system-jpeg-turbo,binary-cache,build-from-source
```

```bash
SKIA_SOURCE_DIR='/path/to/skia' SKIA_LIBRARY_SEARCH_PATH='/path/to/skia/libs' \
SKIA_BUILD_DEFINES="-DSK_HAS_ANDROID_CODEC -DNDEBUG -DSK_SUPPORT_GPU=0 -DSK_ASSUME_GL=1 -DSK_ENABLE_API_AVAILABLE -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -DSK_SUPPORT_PDF -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_USE_LIBGIFCODEC -DSK_CODEC_DECODES_PNG -DSK_ENCODE_PNG -DSK_XML" \
cargo build -v -p skia-safe --no-default-features
```

I've also added an output file `ninja_defines.txt`, which makes getting values for `SKIA_BUILD_DEFINES` easier.

This PR doesn't address any other open issues I've found, but it might make it easier to do #10 and #453. It also means I'm happy to close an old issue of mine #429.

### CODE REVIEW

**Comment by therealbnut** [comment]
Hmm, I’ll have a look into the build errors tomorrow (late at night for me at the moment)

**Comment by therealbnut** [comment]
I'm trying to reproduce this now, running this on MacOS 10.15.7:
```
cargo clean
cargo build -p skia-safe --all-targets --release --features "gl,metal,textlayout,vulkan,webp" --target x86_64-apple-darwin
```
I even tried entirely removing `target` first...
```
rm -rf ./target/
```
I'm not sure how to get better output from `gn`. Although as that's what's failing I suspect it's something to do with `skia/tools/git-sync-deps`. My next steps are to verify that it is being called in the same way as it was before this PR - although I'm not sure why it would work locally, unless there's some special casing for CI.

**Comment by therealbnut** [comment]
@pragmatrix should be ready for review now!

The last several commits are fixing clippy issues that seemed to be on master, I'm not sure if my changes are wanted - if you like I can split them out into a separate PR we can merge first.

To review the rest of this PR I've left some notes in the PR description, although if you wanted to follow the first few commit one at a time it should guide through you through what changed, and allow you to skip over a majority of the changes. I had one mistake where I passed the wrong boolean (to indicate offline builds), but that's fixed now.

I think it would be good to add a test for this new functionality, but I didn't want to mess with your CI stuff.

The way I was thinking of doing this is something like this:

 * build (or copy from another build) the skia libraries (`out/*.a`) and `ninja_defines.txt` into a temporary directory
 * set `SKIA_SOURCE_DIR` to `skia-bindings/skia`
 * set `SKIA_BUILD_DEFINES` from `ninja_defines.txt`
 * set `SKIA_LIBRARY_SEARCH_PATH` to your temporary directory
 * run `cargo build -v -p skia-safe --no-default-features` with whichever features you want, and run whichever tests you want
 
The `skia-bindings` target builds pretty quickly with these settings, so it shouldn't add much overhead, especially if you're doing it with libraries from an existing build.

**Comment by pragmatrix** [comment]
Skipping over the changes, I had a few thoughts:

- I like the separation of the Skia build steps into separate files, this was long overdue.
- The Clippy changes should be separated, I'll prepare a PR against master, and will rebase this one. I hope you don't mind.
- Can we avoid the additional feature flag? This time, there seem no changes in the `[dependencies]` and the additional code to compile is negligible. I suspect that we can make the change in behavior base on the existence of `SKIA_LIBRARY_SEARCH_PATH`?.

> I think it would be good to add a test for this new functionality, but I didn't want to mess with your CI stuff.

We can take care of that after the merge. I think an additional workflow that runs supplementary builds for verifying certain configurations should be added.

Also some rename suggestions: 
- `build_skia/` -> `skia/` (because it's already under `build_support/`).
- `ninja_defines.txt` -> `skia-defines.txt` (contents are related more to the Skia library than to build system and text files should probably not follow Rust conventions, and I think `-` feels a bit more natural to type)
- `bind_skia.rs` -> `skia_bindgen.rs`

**Comment by therealbnut** [comment]
@pragmatrix thanks for the feedback, that all sounds good!

I had the feature flag early on because I was expecting more concrete dependencies but that simplifies things.

**Comment by therealbnut** [comment]
As a side note: I liked the symmetry of build and bind as separate "features". Perhaps in a future PR the bind things can be moved out of build_support as its own module.

**Comment by therealbnut** [comment]
@pragmatrix those changes should be in now - I'm just running locally `cargo +beta clippy` but I don't expect any issues

**Comment by therealbnut** [comment]
@pragmatrix clippy was all good locally - I think the only outstanding change is rebasing on your clippy PR, I'm happy if you want to do that :)

**Comment by therealbnut** [comment]
Thanks for the review and rebase :)

**Pull request merged**
