### PR TITLE
Build crate packages on Azure and deliver them to rust-skia.

### LINKED ISSUE #110: Build, verify, and deploy cargo crates of skia-bindings and skia-safe to rust-skia.
Now that #97 has landed, the next step to prepare for official crate releases is to build and verify the crates on the CI server and release them to the ~~skia-binaries~~rust-skia repository. The resulting `.crate` files are platform and feature independent, so we can create and verify them without an initial build in a separate Azure Pipelines job, but I would rather create them _after_ a binaries package was created so that the verification _already_ pulls in the previously built binary from the regular build and indirectly so tests the binary package downloader with each CI build. 

For a first setup, I think we should limit the crate generation to "Linux stable" for now.

### PR DESCRIPTION
**Pull request by pragmatrix**
Closes #110

### CODE REVIEW

**Comment by pragmatrix** [comment]
I think now that it's fine to deliver them to rust-skia, as long as they are marked as pre-releases.

**Comment by pragmatrix** [comment]
Crates are looking good: https://github.com/rust-skia/rust-skia/releases/tag/0.10.1

**Comment by Brooooooklyn** [comment]
Looks great

**Comment by pragmatrix** [comment]
@Brooooooklyn Thanks! I've updated the readme accordingly.

**Pull request merged**
