### PR TITLE
Add custom logo/icon for skia-rs.

### PR DESCRIPTION
**Pull request by AlbertoGP**
Done from scratch to avoid legal issues, combines elements
resembling the Rust and SKIA logos.

My proposal for #53

### CODE REVIEW

**Comment by pragmatrix** [comment]
[Rendered](https://github.com/rust-skia/rust-skia/blob/9d767e72584e3c6d1e8f2c26ea942729eedcc8d6/skia-rs-logo.svg)

@AlbertoGP I appreciate your effort, but don't like it. So I've just created the most obvious variant of a combined Skia / Rust logo and asked Google for a Brand Permission:

rust-skia-white-inner

If we don't get a permit to use it, I suggest we should take the Rust gear and put a stylistic representation of a what a graphics library represents inside the gear, a paintbrush / palette for example. 

Another idea I just had is to use the gear like in the logo above and _fill_ it half with colorful paint, so that the gear acts as a flatland bucket for a number of different colors and prevents them from pouring out thereby stressing the importance of the safety Rust offers.

Also note that the Rust logo is under a creative commons license and can be used and modified freely.

**Comment by AlbertoGP** [comment]
Yes, if allowed this is the best design.

**Comment by pragmatrix** [comment]
Update: Google Open Source  / Google Brand Permissions rejected the licensing request quite kindly.

**Comment by AlbertoGP** [comment]
I’ve committed a more polished version: [Rendered](https://github.com/rust-skia/rust-skia/blob/ebcde85eb3e6d7e8afd7dd15d7793888e414f658/skia-rs-logo.svg)

**Comment by pragmatrix** [comment]
I like the new one a lot more. The diamond-like center shape is impressive.

But I am not so sure about the letters in the gear. I suspect that they are hard or even impossible to read at smaller sizes. And even at larger sizes, reading around the gear counter-clockwise takes a bit of a toll to my cognitive system.

So I'd rather prefer them not to be in the gear at all, which would make the logo more abstract, but also easier to the eyes while adding more weight to the center shape. But I leave this is up to you.

@Brooooooklyn What do you think?

**Comment by AlbertoGP** [comment]
Hi, I have made a new iteration, removing the letters to leave the gear / chain ring much more similar to the original Rust logo. In retrospect, pushing the letters there was an interesting experiment but it’s better to have it more abstract as you propose.

I’ve also replaced the hand-drawn SVG with a Rust program which I think is the most proper form for the design in the case of a graphics library like this one. It computes the position of all the gear teeth etc. based on parameters such as the number of teeth and wheel radius.

You can run it with `cargo run --example icon`.

It has a single optional parameter which is the size in pixels of the PNG file you want to write.
Without parameters, it’ll produce PNG frames for the animated version.
I avoided using an argument handling package like `clap` to keep the dependencies for this simple example to exactly one: `skia-safe`

Here there is a video of the animated result set to some music:
https://matracas.org/tmp/rust-skia-demo.webm

**Comment by Brooooooklyn** [comment]
@pragmatrix ehh, actually I have no sense in design or any related fields. So feel free to make decision on the logo things, I will approve.

**Comment by pragmatrix** [comment]
@AlbertoGP I can't express how excited I am about the video and the example code. This is a fine piece of art.

To wrap this up, the example code needs to be rust-formatted and the branch rebased on master to get through the CI, then add the logo/icon (no animation) on top of the the `/README.md`  including your credits, and put the generated logo itself in a subdirectory `/artwork`. The Examples section should be extended with a hint on how to generate the logo and a link to the video.

There is already a [github.io repository](https://github.com/rust-skia/rust-skia.github.io) for external resources that lifts some weight from this repository, so if you'd like to link to the video without depending on matracas.org, I'd appreciate a PR just give me permission to copy all the resources, then I'll take care of that.

**Comment by AlbertoGP** [comment]
I’ve run `rustfmt` on it, and added the rendered version and the `README.md` changes.

For the video, I’m trying to reach the author of the music track to get permission.
Until then, will keep it temporarily (hence the `/tmp/` part) at the URL above.

As for the CI, I’ve rebased several times during the last days but it still fails.
Is there some specific git workflow I should follow to satisfy it?

**Comment by pragmatrix** [comment]
@AlbertoGP The README.md looks great.

One more rebase will fix the Skia build errors on Linux (#212), and in addition to that you need to make sure that a `cargo clippy` succeeds without warnings (take a look at the [Windows / macOS CI errors](https://dev.azure.com/pragmatrix-github/rust-skia/_build/results?buildId=2102&view=logs) what to expect). I am fine with `#![allow(clippy::xxx)]` statements at the beginning of `main.rs` if fixing them is too much of a hassle or does not make sense.

**Comment by pragmatrix** [comment]
@AlbertoGP This looks ready now. I would like to merge it and change the link to the animation later if needed.

And assuming that you give your permission, I would like to add your username to the README under a new section "Notable Contributions".

**Comment by AlbertoGP** [comment]
Yes, the video will stay for now as the version without sound, until I get a response from the musician. Feel free to change/remove the link in any way later.
As for mentioning my user name in the README, I have nothing against.

Please merge this pull request at your earliest convenience.

**Pull request merged**
